apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-js-frontend.fullname" . }}
  labels:
    {{- include "node-js-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "node-js-frontend.selectorLabels" . | nindent 4 }}
