name: Deploy Application

on:
  push:
    tags:
      - 'node-js-frontend-[0-9]+.[0-9]+.[0-9]+'
env:
  APP_NAME: node-js-frontend
  REGISTRY: ghcr.io/mikescholl-sysdig/my-demo-application

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/setup-helm@v3
      with:
         token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
      id: install

    - name: Deploy Helm Chart
      run: |
        mkdir ~/.kube 
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        KUBECONFIG=~/.kube/config
        ${{ steps.install.outputs.helm-path }} upgrade node-js-frontend --install --namespace my-node-app ./node-js-frontend -f ./node-js-frontend/values.yaml
      shell: bash